#!/bin/bash

load_config() {
  [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
  UNRAID_API_KEY="${UNRAID_API_KEY:-}"
  UNRAID_API_HOST="${UNRAID_API_HOST:-http://localhost}"
  MQTT_HOST="${MQTT_HOST:-localhost}"
  MQTT_PORT="${MQTT_PORT:-1883}"
  MQTT_PROTOCOL="${MQTT_PROTOCOL:-mqtt}"
  MQTT_BASE_TOPIC="${MQTT_BASE_TOPIC:-homeassistant}"
  MQTT_DEVICE_ID="${MQTT_DEVICE_ID:-unraid}"
  MQTT_DEVICE_NAME="${MQTT_DEVICE_NAME:-Unraid Server}"
  MQTT_TOPIC="${MQTT_TOPIC:-${MQTT_DEVICE_ID}}"
  PLUGIN_ENABLED="${PLUGIN_ENABLED:-true}"
  HA_WATCH_STATUS="${HA_WATCH_STATUS:-true}"
  HA_STATUS_TOPIC="${HA_STATUS_TOPIC:-homeassistant/status}"
  HA_DISCOVERY_TOPIC="${HA_DISCOVERY_TOPIC:-homeassistant}"
  AVAILABILITY_TOPIC="${MQTT_BASE_TOPIC}/${MQTT_TOPIC}/availability"
  INTERVAL_ARRAY_STATUS="${INTERVAL_ARRAY_STATUS:-30}"
  INTERVAL_ARRAY_SUMMARY="${INTERVAL_ARRAY_SUMMARY:-60}"
  INTERVAL_CACHE="${INTERVAL_CACHE:-60}"
  INTERVAL_PARITY="${INTERVAL_PARITY:-60}"
  INTERVAL_REBUILD="${INTERVAL_REBUILD:-30}"
  INTERVAL_SYSTEM_INFO="${INTERVAL_SYSTEM_INFO:-3600}"
  INTERVAL_UPDATE_AVAILABLE="${INTERVAL_UPDATE_AVAILABLE:-3600}"
  INTERVAL_UPTIME="${INTERVAL_UPTIME:-60}"
  INTERVAL_DISK_TEMPS="${INTERVAL_DISK_TEMPS:-60}"
  INTERVAL_DISK_STATES="${INTERVAL_DISK_STATES:-30}"
  INTERVAL_DISK_USAGE="${INTERVAL_DISK_USAGE:-300}"
  INTERVAL_DISK_ERRORS="${INTERVAL_DISK_ERRORS:-300}"
  INTERVAL_MONITOR="${INTERVAL_MONITOR:-60}"
  INTERVAL_NETWORK="${INTERVAL_NETWORK:-30}"
  INTERVAL_SHARES="${INTERVAL_SHARES:-300}"
}

build_mqtt_args() {
  MQTT_ARGS=(-h "$MQTT_HOST" -p "$MQTT_PORT")
  case "$MQTT_PROTOCOL" in
    mqtts|wss)
      MQTT_ARGS+=(--cafile "${MQTT_CA_CERT}")
      [ -n "$MQTT_CLIENT_CERT" ] && MQTT_ARGS+=(--cert "$MQTT_CLIENT_CERT" --key "$MQTT_CLIENT_KEY")
      [ "$MQTT_TLS_INSECURE" = "true" ] && MQTT_ARGS+=(--insecure)
      ;;
  esac
  [ -n "$MQTT_USER" ] && MQTT_ARGS+=(-u "$MQTT_USER" -P "$MQTT_PASS")
}
