#!/bin/bash

load_config() {
  [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
  MQTT_HOST="${MQTT_HOST:-localhost}"
  MQTT_PORT="${MQTT_PORT:-1883}"
  MQTT_PROTOCOL="${MQTT_PROTOCOL:-mqtt}"
  MQTT_BASE_TOPIC="${MQTT_BASE_TOPIC:-homeassistant}"
  MQTT_DEVICE_ID="${MQTT_DEVICE_ID:-unraid}"
  MQTT_DEVICE_NAME="${MQTT_DEVICE_NAME:-Unraid Server}"
  MQTT_TOPIC="${MQTT_TOPIC:-${MQTT_DEVICE_ID}}"
  PLUGIN_ENABLED="${PLUGIN_ENABLED:-true}"
  HA_WATCH_STATUS="${HA_WATCH_STATUS:-true}"
  HA_STATUS_TOPIC="${HA_STATUS_TOPIC:-homeassistant/status}"
  HA_DISCOVERY_TOPIC="${HA_DISCOVERY_TOPIC:-homeassistant}"
  AVAILABILITY_TOPIC="${MQTT_BASE_TOPIC}/${MQTT_TOPIC}/availability"
  RETAIN_ARRAY_STATUS="${RETAIN_ARRAY_STATUS:-true}"
  RETAIN_ARRAY_SUMMARY="${RETAIN_ARRAY_SUMMARY:-true}"
  RETAIN_CACHE="${RETAIN_CACHE:-true}"
  RETAIN_PARITY="${RETAIN_PARITY:-true}"
  RETAIN_REBUILD="${RETAIN_REBUILD:-true}"
  RETAIN_SYSTEM_INFO="${RETAIN_SYSTEM_INFO:-true}"
  RETAIN_DISK_TEMPS="${RETAIN_DISK_TEMPS:-true}"
  RETAIN_DISK_STATES="${RETAIN_DISK_STATES:-true}"
  RETAIN_DISK_USAGE="${RETAIN_DISK_USAGE:-true}"
  RETAIN_DISK_ERRORS="${RETAIN_DISK_ERRORS:-true}"
  RETAIN_DISK_JSON="${RETAIN_DISK_JSON:-true}"
  RETAIN_SMART="${RETAIN_SMART:-true}"
  RETAIN_RW_SPEEDS="${RETAIN_RW_SPEEDS:-true}"
  RETAIN_MONITOR="${RETAIN_MONITOR:-true}"
  RETAIN_NETWORK="${RETAIN_NETWORK:-true}"
  RETAIN_SHARES="${RETAIN_SHARES:-true}"
  RETAIN_UPTIME="${RETAIN_UPTIME:-true}"
}

build_mqtt_args() {
  MQTT_ARGS=(-h "$MQTT_HOST" -p "$MQTT_PORT")
  case "$MQTT_PROTOCOL" in
    mqtts|wss)
      MQTT_ARGS+=(--cafile "${MQTT_CA_CERT}")
      [ -n "$MQTT_CLIENT_CERT" ] && MQTT_ARGS+=(--cert "$MQTT_CLIENT_CERT" --key "$MQTT_CLIENT_KEY")
      [ "$MQTT_TLS_INSECURE" = "true" ] && MQTT_ARGS+=(--insecure)
      ;;
  esac
  [ -n "$MQTT_USER" ] && MQTT_ARGS+=(-u "$MQTT_USER" -P "$MQTT_PASS")
}
